services:
  app:
    image: srinjay2004/enderbrary-api:latest
    container_name: endrlink-backend
    environment:
      - ACTIVE_PROFILE=dev
      - APP_VERSION=1.0.0
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    ports:
      - 8080:8080
    networks:
      - enderbrary-network
networks:
    enderbrary-network:
      driver: bridge