import type {Metadata} from "next";
import {Comfortaa, Inter} from "next/font/google";
import "./globals.css";
import {UserProvider} from "@/providers/UserContext";
import {Toaster} from "sonner";

const inter = Inter({
    variable: "--font-sans",
    subsets: ["latin"],
})

const comfortaa = Comfortaa({
    variable: "--font-display",
    subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-full antialiased ${inter.variable} ${comfortaa.variable} antialiased`}
      >
      <UserProvider>
          {children}
          <Toaster position={'top-center'}/>
      </UserProvider>
      </body>
    </html>
  );
}
